artifact_location: /home/huyanh/documents/workspaces/mlops/projects/youtube-sentiment-insights/mlflow_tracking_uri/0
creation_time: 1761428678164
experiment_id: '0'
last_update_time: 1761428678164
lifecycle_stage: active
name: Default
